# Generated by Django 2.0.2 on 2018-09-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rx_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rx_claim',
            name='Generic',
        ),
        migrations.RemoveField(
            model_name='rx_claim',
            name='NDCCode',
        ),
        migrations.RemoveField(
            model_name='rx_claim',
            name='PharmacyState',
        ),
        migrations.RemoveField(
            model_name='rx_claim',
            name='TotalCost',
        ),
    ]
